redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Users\\ganes\\Desktop\\New folder\\semantic-garbage-collection\\server\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\ganes\\Desktop\\New folder\\semantic-garbage-collection\\server"
publishOrigin = "default"
base = "C:\\Users\\ganes\\Desktop\\New folder\\semantic-garbage-collection\\server"
functions = "C:\\Users\\ganes\\Desktop\\New folder\\semantic-garbage-collection\\server\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]